/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.
 */

// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: "autogenerated", dirName: "."}],

  // But you can create a sidebar manually

  sidebar: [
    // Ronin Network basics
    {
      type: "category",
      label: "Basics",
      collapsed: false,
      collapsible: false,
      link: {
        type: "generated-index",
        description: "Everything you need to know about Ronin.",
        slug: "/basics",
      },
      items: [
        // Introduction to Ronin
        {
          type: "doc",
          label: "Introduction to Ronin",
          id: "basics/introduction",
        },
        // Acquire RON
        "basics/acquire-ron",
        // Tokenomics
        "basics/tokenomics",
        // Security audits
        "basics/audits",
        {
          type: "category",
          label: "dApps",
          link: {
            type: "generated-index",
            description:
              "User guides for selected dApps in the Ronin ecosystem.",
            slug: "/apps",
          },
          items: [
            // Katana
            {
              type: "category",
              label: "Katana",
              link: {
                type: "doc",
                id: "apps/katana/overview",
              },
              items: [
                // Swap tokens
                "apps/katana/guides/swap-tokens",
                // Liquidity pools
                {
                  type: "category",
                  label: "Liquidity pools",
                  link: {
                    type: "generated-index",
                    description:
                      "Guides for creating and managing liquidity pools.",
                    slug: "apps/katana/pools",
                  },
                  items: [
                    // Create a liquidity pool
                    "apps/katana/guides/create-pool",
                    // Add liquidity to a pool
                    "apps/katana/guides/add-liquidity",
                  ],
                },
                // Farms
                {
                  type: "category",
                  label: "Farms",
                  link: {
                    type: "generated-index",
                    description:
                      "Guides for creating farms and staking LP tokens.",
                    slug: "apps/katana/farms",
                  },
                  items: [
                    // Create a farm
                    "apps/katana/guides/create-farm",
                    // Stake LP tokens
                    "apps/katana/guides/stake-tokens",
                  ],
                },
                // {
                //   type: "link",
                //   label: "Katana Core SDK",
                //   href: "https://github.com/skymavis/katana-sdk/tree/main/packages/katana-core",
                // },
              ],
            },
            // Ronin Safe
            "apps/multisig",
            // Ronin Bridge
            {
              type: "category",
              label: "Ronin Bridge",
              link: {
                type: "doc",
                id: "apps/ronin-bridge/overview",
              },
              items: [
                // Deposit ERC-20 tokens
                "apps/ronin-bridge/guides/deposit-token",
                // Withdraw ERC-20 tokens
                "apps/ronin-bridge/guides/withdraw-token",
                // Deposit NFTs
                "apps/ronin-bridge/guides/deposit-nft",
                // Withdraw NFTs
                "apps/ronin-bridge/guides/withdraw-nft",
                // Token withdrawal limits
                "apps/ronin-bridge/reference/withdrawal-limits",
              ],
            },
            // CCIP Bridge
            {
              type: "category",
              label: "CCIP Bridge",
              link: {
                type: "doc",
                id: "apps/ccip-bridge/overview",
              },
              items: [
                // Transfer ERC-20 tokens
                "apps/ccip-bridge/guides/transfer-token",
              ],
            },
            // Ronin Explorer
            "apps/ronin-explorer",
            // Token Revoke
            "apps/revoke",
            // RNS
            {
              type: "category",
              label: "Ronin Name Service",
              link: {
                type: "doc",
                id: "apps/rns/overview",
              },
              items: [
                {
                  type: "category",
                  label: "Register an RNS name",
                  link: {
                    type: "generated-index",
                    description:
                      "Guides to register different categories of RNS names.",
                    slug: "apps/rns/register",
                  },
                  items: [
                    // Register a regular RNS name
                    "apps/rns/guides/register/regular",
                    // Buy an RNS name at auction
                    "apps/rns/guides/register/auctioned",
                    // Register a protected RNS name
                    "apps/rns/guides/register/protected",
                  ],
                },
                // Manage RNS names
                "apps/rns/guides/manage",
                // Trade RNS names
                "apps/rns/guides/trade",
                // RNS FAQ
                "apps/rns/reference/faq",
              ],
            },
          ],
        },
        // Community
        "basics/community",
        // Contribute to the documentation
        {
          type: "category",
          label: "Contribute",
          link: {
            type: "generated-index",
            description: "Contribute to the Ronin documentation.",
            slug: "/basics/contribute",
          },
          items: [
            // Contribution guide
            "CONTRIBUTING",
            // Content style guide
            "basics/contribute/style-guide",
            // Content templates
            "basics/contribute/templates",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Proof of Distribution",
      collapsed: false,
      collapsible: false,
      link: {
        type: "doc",
        id: "proof-of-distribution/index",
      },
      items: [
        "proof-of-distribution/register",
        "proof-of-distribution/verify",
        "proof-of-distribution/activate",
        "proof-of-distribution/manage",
        "proof-of-distribution/faq",
      ],
    },
    {
      type: "category",
      label: "Developers",
      collapsed: false,
      collapsible: false,
      link: { type: "doc", id: "developers/index" },
      items: [
        {
          type: "category",
          label: "Network",
          link: { type: "doc", id: "developers/network/index" },
          items: [
            {
              type: "category",
              label: "EIP-1559",
              link: { type: "doc", id: "developers/network/eip-1559/index" },
              items: ["developers/network/eip-1559/gas-suggestion"],
            },
          ],
        },
        {
          type: "category",
          label: "Quickstart",
          link: {
            type: "generated-index",
            description:
              "Welcome to the Ronin Quickstart guides! Whether you're a developer looking to integrate with Ronin or just exploring its capabilities, this section provides step-by-step instructions to help you get started quickly.",
            slug: "/developers/quickstart",
          },
          items: [
            "developers/quickstart/read",
            "developers/quickstart/write",
            "developers/quickstart/deploy",
            "developers/quickstart/list-collection",
          ],
        },
        "developers/gold-standard",
        {
          type: "category",
          label: "Node setup",
          link: {
            type: "generated-index",
            description:
              "A Ronin node is the building block of the Ronin network infrastructure. Nodes connect together to conduct consensus on transactions, maintain the ledger, and provide other useful functions.",
            slug: "/developers/nodes",
          },
          items: [
            "developers/nodes/requirements",
            "developers/nodes/setup",
            "developers/nodes/build-from-source",
            "developers/nodes/upgrade-node-version",
          ],
        },
        {
          type: "category",
          label: "Smart Contracts",
          link: {
            type: "doc",
            id: "developers/smart-contracts/deploy",
          },
          items: [
            "developers/smart-contracts/deploy",
            "developers/smart-contracts/verify",
            "developers/smart-contracts/guidelines",
          ],
        },
        {
          type: "category",
          label: "Tools and services",
          link: {
            type: "generated-index",
            description: "Discover Ronin tools or services.",
            slug: "/developers/tools",
          },
          items: [
            "developers/tools/node-providers",
            "developers/tools/api-providers",
            {
              type: "category",
              label: "Oracles",
              link: {
                type: "generated-index",
                description:
                  "Oracles are critical components in the Ronin ecosystem that enable smart contracts to interact with data from the outside world. They serve as bridges between the blockchain and external data sources, providing trusted and verifiable information that smart contracts can use to execute logic.",
                slug: "/oracles",
              },
              items: [
                "developers/tools/oracles/pyth",
                "developers/tools/oracles/chainlink",
                "developers/tools/oracles/api3",
              ],
            },
            "developers/tools/ccip",
            "developers/tools/the-graph",
            "developers/tools/vrf",
            "developers/tools/delegation",
            "developers/tools/faucet",
          ],
        },
        {
          type: "link",
          label: "Ronin Developer Console",
          href: "https://developers.roninchain.com/console",
        },
        {
          type: "link",
          label: "Mavis docs",
          href: "https://docs.skymavis.com/",
        },
      ],
    },
  ],
};

module.exports = sidebars;
